name = "dflix-tmdb-metadata"
main = "src/index.mjs"
compatibility_date = "2026-08-10"
workers_dev = true
preview_urls = false

[[ratelimits]]
name = "TMDB_RATE_LIMITER"
namespace_id = "1001"

  [ratelimits.simple]
  limit = 60
  period = 60
